version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales 
        description: greenweez sales
        tests:
        - unique:
           column_name: "(orders_id || '-' || pdt_id)"
          
      - name: product
        identifier: raw_gz_product 
        description: greenweez products
        columns:
          - name: products_id
            tests:
             - unique
             - not_null
                    
      - name: ship
        identifier: raw_gz_ship
        description: greenweez ships
        columns:
          - name: orders_id
            tests:
             - unique
             - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: gz_raw_data

      - name: bing
        identifier: raw_gz_bing
        description: gz_raw_data

      - name: criteo
        identifier: raw_gz_criteo
        description: gz_raw_data

      - name: facebook
        identifier: raw_gz_facebook
        description: gz_raw_data

       


